[tool.isort]
force_single_line = true
force_alphabetical_sort_within_sections = true
lines_after_imports = 2

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 120
exclude = ["venv"]
